version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image:
- Visual Studio 2017
- Ubuntu
configuration: Release
init:
- pwsh: |
    $encoding = New-Object System.Text.UTF8Encoding($false)
    $text = "[https://www.transifex.com]`r`nhostname = https://www.transifex.com`r`npassword = $env:TRANSIFEX_TOKEN`r`nusername = api"
    $path = [System.IO.Path]::Combine("$env:USERPROFILE\.transifexrc")
    [System.IO.File]::WriteAllText($path, $text, $encoding)
    if (!(Test-Path "$env:TRANSLATION_DIR")) { mkdir "$env:TRANSLATION_DIR" }
environment:
  TRANSIFEX_TOKEN:
    secure: bsNgsw7B/HOGMSp7RidtPLru9aI8LAndBI1/TMPC7RcC897hXAoIyYJup6abXR/S
  TRANSLATION_DIR: '%HOME%/translations'
install:
- cmd: cinst transifex-client --ignore-dependencies
- sh:  pip install transifex-client
cache:
- '%TRANSLATION_DIR%'
- 'tools -> tools/packages.config'
build_script:
- pwsh: |
    cp "$env:TRANSLATION_DIR/*.resx" "$env:APPVEYOR_BUILD_FOLDER/src/Hello-Transifex/Properties/" -Force
    .\build.ps1 -Target "Create-ZipFile" -Verbosity Diagnostic -Configuration $env:CONFIGURATION
    cp "$env:APPVEYOR_BUILD_FOLDER/Hello-Transifex/Properties/*.resx" "$env:TRANSLATION_DIR/" -Force -Exclude "Resources.resx"
    Compress-Archive -Path "$env:APPVEYOR_BUILD_FOLDER/*.resx" -CompressionLevel Optimal -DestinationPath translation-cache.zip
test: off
artifacts:
- path: '**/*.zip'
