version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image:
- Visual Studio 2017
- Ubuntu
configuration: Release
environment:
  TRANSIFEX_TOKEN:
    secure: bsNgsw7B/HOGMSp7RidtPLru9aI8LAndBI1/TMPC7RcC897hXAoIyYJup6abXR/S
  TRANSLATION_DIR: 'translations'
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: '-t7z -m0=lzma -mx=9'
install:
- pwsh: if (!(Test-Path "$env:TRANSLATION_DIR")) { mkdir "$env:TRANSLATION_DIR" }
- cmd: cinst transifex-client --ignore-dependencies
- sh:  |
    sudo apt-get -y install python3-pip
    sudo pip3 install transifex-client
cache:
- '%TRANSLATION_DIR%'
- 'tools -> tools/packages.config'
build_script:
- pwsh: Copy-Item "$env:TRANSLATION_DIR/*.resx" "$env:APPVEYOR_BUILD_FOLDER/src/Hello-Transifex/Properties/" -Force

- cmd: powershell -command "pushd $env:APPVEYOR_BUILD_FOLDER ; .\build.ps1 -Target 'Create-ZipFile' -Verbosity Diagnostic -Configuration $env:CONFIGURATION"
- sh: bash ./build.sh --target='Create-ZipFile' --verbosity=Diagnostic --configuration=$Configuration

- pwsh: Copy-Item "$env:APPVEYOR_BUILD_FOLDER/src/Hello-Transifex/Properties/*.resx" "$env:TRANSLATION_DIR/" -Force -Exclude "Resources.resx"
- cmd: 7z a translations.7z "%TRANSLATION_DIR%\*.resx" %APPVEYOR_CACHE_ENTRY_ZIP_ARGS%
- sh: 7z a translations.7z "$TRANSLATION_DIR/*.resx" $APPVEYOR_CACHE_ENTRY_ZIP_ARGS
test: off
artifacts:
- path: '**/*.zip'
- path: '**/*.7z'
