version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image:
- Visual Studio 2017
- Ubuntu
configuration: Release
init:
- sh: export USERPROFILE=$HOME
- pwsh: |
    $encoding = New-Object System.Text.UTF8Encoding($false)
    $text = "[https://www.transifex.com]`r`nhostname = https://www.transifex.com`r`npassword = $env:TRANSIFEX_TOKEN`r`nusername = api"
    $path = [System.IO.Path]::Combine("$env:USERPROFILE", ".transifexrc")
    [System.IO.File]::WriteAllText($path, $text, $encoding)
environment:
  TRANSIFEX_TOKEN:
    secure: bsNgsw7B/HOGMSp7RidtPLru9aI8LAndBI1/TMPC7RcC897hXAoIyYJup6abXR/S
  TRANSLATION_DIR: 'translations'
install:
- pwsh: if (!(Test-Path "$env:TRANSLATION_DIR")) { mkdir "$env:TRANSLATION_DIR" }
- cmd: cinst transifex-client --ignore-dependencies
- sh:  |
    sudo apt install python-pip
    sudo pip install transifex-client
cache:
- '%TRANSLATION_DIR%'
- 'tools -> tools/packages.config'
build_script:
- pwsh: |
    cp "$env:TRANSLATION_DIR/*.resx" "$env:APPVEYOR_BUILD_FOLDER/src/Hello-Transifex/Properties/" -Force
    .\build.ps1 -Target "Create-ZipFile" -Verbosity Diagnostic -Configuration $env:CONFIGURATION
    cp "$env:APPVEYOR_BUILD_FOLDER/src/Hello-Transifex/Properties/*.resx" "$env:TRANSLATION_DIR/" -Force -Exclude "Resources.resx"
- cmd: 7x a translations.zip "%TRANSLATION_DIR%\*.resx" # This is just so we can see what files we have cached
- sh: tar cvpjf translations.tar.bz2 "$TRANSLATION_DIR/*.resx"
test: off
artifacts:
- path: '**/*.zip'
