version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
environment:
  TRANSIFEX_TOKEN:
    secure: G7OCUFTUfOC89yjju3g64LeF3aTqCL5wJdQ+Y2Wa+/TXHUFjdD+SACbwZcIujuBJ
init:
- ps: >-
    $encoding = New-Object System.Text.UTF8Encoding($false)

    $text = "[https://www.transifex.com]`r`nhostname = https://www.transifex.com`r`npassword = $env:TRANSIFEX_TOKEN`r`nusername = api"

    [System.IO.File]::WriteAllText("$env:USERPROFILE\.transifexrc", $text, $encoding)
install:
- cmd: pip install transifex-client
build_script:
- ps: .\build.ps1 -Target "Create-ZipFile"
test: off
artifacts:
- path: '**/*.zip'